services:
  vue-app:
    build: .
    container_name: frontend-app
    ports:
      - "5173:5173"
    volumes:
      - ./App:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["npm", "run", "dev", "--", "--host"]
    networks:
      - shared_network

networks:
  shared_network:
    external: true