name: Coverage

on:
  push:
    branches:
      - main

jobs:
  update-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          cd App
          npm install

      - name: Run coverage
        run: |
          cd App
          # Il seguente comando genera la coverage in console e la reindirizza su coverage.txt
          npm run test:coverage > coverage.txt

      - name: Prepend coverage into README
        run: |
          node .github/scripts/prepend-coverage.js

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Aggiorna coverage in README [skip ci]" || echo "Nessuna modifica da commitare"
          git push
        # ^ Se non ci sono differenze reali, la commit fallisce
        #   e va in "|| echo" così non interrompi il workflow.
